- pydatalab/docs/design/models.md
- pydatalab/pydatalab/models/__init__.py
- pydatalab/pydatalab/models/cells.py
- pydatalab/pydatalab/routes/v0_1/items.py
- pydatalab/schemas/cell.json
- pydatalab/tests/conftest.py
- pydatalab/tests/routers/test_samples.py
- pydatalab/tests/test_models.py
- webapp/cypress/e2e/batchSampleFeature.cy.js
- webapp/src/components/BatchCreateSampleModal.vue
- webapp/src/server_fetch_utils.js
This PR adds a cell data model that is stored as an item. It is currently created with the `create_sample` endpoint.
https://www.youtube.com/watch?v=ZRcpnM26nJM
> Add data model for cells

- webapp/src/views/EditPage.vue
Updating font awesome seems to have changed the way this one icon is sized. This change makes it similar to the original size.
> Fix sizing of EditPage "save" icon

- pydatalab/Pipfile
- pydatalab/Pipfile.lock
- pydatalab/pydatalab/main.py
From some quick investigation, I think most of the load time on edit pages is actually the time spent in sending the large bokeh plots over network. We might be able to speed this up by compressing routes, which `flask-compress` does nicely. The caveat is that this will only speed things up if the time spent compressing is less than the network time. I'm guessing it will be, but we can check once deployed.
This currently compresses all routes, but probably we only need to compress the very large routes.
> Add compression to heavy routes

- pydatalab/pydatalab/main.py
- pydatalab/pydatalab/routes/v0_1/auth.py
Addresses #205, but does not yet close it.
Would be nice to make a login modal to replace the current direct link to `/login/github` that could link to the appropriate OAuth provider endpoints, e.g., "Sign in with Github" and "Sign in with ORCID"
> Intercept flask-dance redirects and point back to HTTP referer

- webapp/src/field_utils.js
closes #308 by making the generic computed getters in `field_utils.js` automatically save null whenever an empty string is provided. This doesn't seem to break any existing functionality that I could find, but we should monitor.
> Fix empty string in float value bug

- webapp/src/field_utils.js
In #309, added a fix that had the item computed setter in field_utils.js automatically replace `""` with `null`. Now, do the same for block fields.
> Fix empty string in float value bug, part 2

- pydatalab/pydatalab/models/cells.py
- pydatalab/pydatalab/routes/v0_1/graphs.py
- pydatalab/pydatalab/routes/v0_1/items.py
- pydatalab/schemas/cell.json
- pydatalab/tests/conftest.py
- pydatalab/tests/routers/test_graph.py
- pydatalab/tests/test_models.py
- webapp/src/components/ItemGraph.vue
- webapp/src/components/RelationshipVisualization.vue
- webapp/src/server_fetch_utils.js
- webapp/src/views/ItemGraphPage.vue
- filter out deleted nodes in graph endpoint
- add relationships to cells and render cells in the graph
- re-enable user interaction with the graph (zoom/pan etc.)
- add graph endpoint specialization for graph centred on given item
> Graph view updates: filter out deleted nodes, add cells and item-centred graphs

- webapp/package.json
- webapp/src/components/FancySampleTable.vue
- webapp/src/components/FancyStartingMaterialTable.vue
- webapp/src/components/SampleTable.vue
- webapp/src/router/index.js
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
- webapp/src/views/Samples.vue
- webapp/src/views/SamplesNext.vue
- webapp/src/views/StartingMaterialsNext.vue
- webapp/yarn.lock
Adding in a proper (third party) data table component to add quality of life improvements like sorting, searching, and batch operations to the item tables in the UI.
> Add sortable, paginated data table under `/next`

- pydatalab/pydatalab/file_utils.py
- pydatalab/pydatalab/logger.py
- pydatalab/tests/conftest.py
Old file sync logic:
1. If marked as `is_live` (any remote synced echem file), check local copy of file and see if it is older than the minimum cache age (a few days)
2. If so, redownload the file and update the database with the current timestamp
i.e., every single file is redownloaded for echem.
New logic:
1. If marked as `is_live`, call `stat` on the remote file and check if it is newer than the local version with some minimum difference of 1 hour.
2. If so, resync. If not, and the remote stat is older than 31 days, also mark the file as no longer `is_live`, such that future checks are not performed. This makes the echem block load about 100 times faster (as confirmed by timing the debug logs, also added in this PR).
> Mark remote files as not live if not written to within some period

- pydatalab/Pipfile
- pydatalab/Pipfile.lock
- pydatalab/pydatalab/blocks/echem_block.py
- pydatalab/pydatalab/bokeh_plots.py
- pydatalab/tests/blocks/test_echem_block.py
This PR starts to rework the echem block with the aim of closing #339 and improving performance for larger files.
This is achieved by caching the parsed dataframes to disk alongside the attached files proper. This could be built out into a proper storage backend, e.g., additional suffixed files in the same remote directory as the attached file, which could also allow us to begin transitioning over to GridFS or some other blob storage. All use of the block-level cache has been removed as it never did anything.
#339 is closed by updating the navani subdep to fix the cycle summary behaviour for arbin files, where previously one column name was missing.
Outstanding issue: big files can take longer than 60 seconds to parse, which causes the network to timeout and gunicorn kills the request. …
> Fixes for arbin and optimisations for large echem files

- pydatalab/pydatalab/models/cells.py
As reported by @Gesaph, the UI was not dealing with this constraint well, and its probably superfluous anyway, so I have removed it.
> Remove constraints on 'other' cell format requiring a description

- webapp/src/components/BatchCreateSampleModal.vue
- webapp/src/components/CreateSampleModal.vue
- webapp/src/components/FileSelectModal.vue
Adds `scroll:auto` to the sample creation modal so that it will scroll if on a small screen. closes #332
Also updates the vue deep css selectors from the old syntax (`>>>`) to the modern (`:deep`) syntax.
> Add sample modal scroll

- webapp/src/components/datablocks/ChatBlock.vue
Enter now sends the message, and shift-enter (probably meta-enter, ctrl-enter, etc. too) makes a newline. This mimics the behavior of other messaging apps.
> chatblock: swap behavior of shift and shift-enter

- pydatalab/pydatalab/models/cells.py
- pydatalab/pydatalab/models/entries.py
- pydatalab/pydatalab/models/samples.py
- pydatalab/pydatalab/models/utils.py
- pydatalab/pydatalab/mongo.py
- pydatalab/schemas/cell.json
- pydatalab/schemas/sample.json
- pydatalab/tests/test_models.py
- webapp/cypress/e2e/batchSampleFeature.cy.js
- webapp/cypress/e2e/editPage.cy.js
- webapp/cypress/e2e/sampleTablePage.cy.js
- webapp/src/components/CompactConstituentTable.vue
- webapp/src/components/FormattedItemName.vue
- webapp/src/components/ItemSelect.vue
- webapp/src/components/SynthesisInformation.vue
This PR allows samples to have inlined synthesis consituents, determined by name only. These inline references do not populate the relationships field.
This PR refactors the cell component and constituents to use the same models (with a new alias in case we want to extend one), and uses the same Vue component for the constituents table between samples and cells.
To-do/discuss:
> Allow inline references for samples, and other tweaks

- pydatalab/pydatalab/blocks/echem_block.py
When attempting to load a new live file into the cycle block, the page crashes with `"Error getting sample data: ("local variable 'cycle_summary_df' referenced before assignment",)` and the sample can no longer be opened.
I believe this is just a simple bug where `cycle_summary_df` is never set (to `None`) for live files. Hopefully moving this one line fixes the issue.
> fix cycle block bug that prevents use of live echem files

- pydatalab/Pipfile
- pydatalab/Pipfile.lock
- pydatalab/pydatalab/apps/chat/blocks.py
- webapp/src/components/ChatWindow.vue
- webapp/src/components/MessageBubble.vue
- webapp/src/components/datablocks/ChatBlock.vue
- webapp/src/server_fetch_utils.js
- webapp/src/views/EditPage.vue
Collecting miscellaneous fixes and improvements for the chat block, carrying on from previous progress on this big checklist (see #356 ):
> Further chatblock improvements

- pydatalab/pydatalab/routes/v0_1/items.py
- webapp/src/components/datablocks/DataBlockBase.vue
- webapp/src/field_utils.js
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
- webapp/src/views/EditPage.vue
This PR should dramatically help how responsive the site feels, by first loading the page without passing the blocks through DataBlock objects (potentially triggering plotting, etc.) and _then_ asynchronously updating the blocks by calling `updateBlockFromServer` on each individual block. This means the page should load quickly with slower plots, etc. potentially coming in later.
> Load blocks asynchronously

- webapp/vue.config.js
The website title has previously been set to the webpack package name. This change allows it to be configured using the `VUE_APP_WEBSITE_TITLE` environment variable. If this variable is not set, defaults to "datalab".
Example use:
in `.env`:
```bash
VUE_APP_WEBSITE_TITLE="datalab - Grey group"
```
> make website title setable by environment variable

- pydatalab/pydatalab/blocks/blocks.py
Bruker NMR files can each have a different set of "process numbers". This PR is a small bugfix to automatically select an existing process if the block has an invalid process number selected for any reason ( _i.e._ if the filename has just been changed and the selected process is not a valid process number in the new experiment).
Closes #402
> NMR block process number bugfix

- pydatalab/pydatalab/apps/chat/blocks.py
- webapp/src/components/datablocks/ChatBlock.vue
- webapp/src/field_utils.js
A few improvements to the chatblock:
-The prompt is tweaked to work better (shorter intro message, and more likely to produce mermaid code that compiles)
-The block title is changed to "virtual assistant"
-"show prompts" has been changed to "show advanced" and also allows the user to set the temperature and see the model name.
-fixed a bug in `field_utils.js` where values couldn't be set to 0.
> Chat improvements

- CITATION.cff
This is to enable easier automated archives for each release on Zenodo.
> Add CITATION.cff file for repository

- pydatalab/pydatalab/models/people.py
- pydatalab/pydatalab/routes/utils.py
- pydatalab/schemas/cell.json
- pydatalab/schemas/sample.json
- pydatalab/schemas/startingmaterial.json
This is a quick hack for one-to-many permissions for samples, e.g., one "manager" can see entries from any user that lists their ID as a manager. 
This should be iterated on to allow for proper group permission control, but think this is a useful start. Currently managers also have write access to the sample, but this can be discussed.
> Add concept of user manager permissions

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/file_utils.py
- pydatalab/pydatalab/remote_filesystems.py
- pydatalab/pydatalab/routes/v0_1/__init__.py
- pydatalab/pydatalab/routes/v0_1/remotes.py
- pydatalab/tasks.py
- pydatalab/tests/conftest.py
- pydatalab/tests/routers/test_remotes.py
- pydatalab/tests/test_config.py
- pydatalab/tests/test_remote_filesystems.py
- webapp/src/components/TreeMenu.vue
- webapp/src/server_fetch_utils.js
This PR adds a series of fixes for remote filesystems, in particular making them more robust to expected failures, e.g., host key changes or folders being removed.
Previously, an JSON unhandled error regarding a single remote would break the entire `/list-remote-directories` response, but now the error is nested within that remote (closes #428).
It adds an admin task `invoke admin.check-remotes` that can check the sync status of remotes individually using a new endpoint for listing a single remote (could be used in the future by the app for selective syncing).
> Remote filesystem scanning improvements

- pydatalab/pydatalab/apps/echem/__init__.py
- pydatalab/pydatalab/apps/echem/blocks.py
- pydatalab/pydatalab/apps/echem/utils.py
- pydatalab/pydatalab/blocks/__init__.py
- pydatalab/tests/blocks/test_echem_block.py
> Move echem block to its own app submodule

- pydatalab/pydatalab/apps/echem/utils.py
- pydatalab/pydatalab/bokeh_plots.py
- webapp/src/components/datablocks/CycleBlock.vue
Closes #420
Bit janky, but filters the cycle inputs better to prevent infinite loops of plot crashes when invalid cycles are provided. Now, 0 is explicitly banned in JS, and values beyond the maximum number of cycles should tap out and only plot the final cycle. 
Putting a range of values above the max value will still crash the plotter, but it will just fallback to the previous plot without raising a UI error (maybe need to consider this more).
> Better sanitize inputs for plot cycle selector

- pydatalab/pydatalab/routes/v0_1/info.py
- webapp/src/components/StatisticsTable.vue
- webapp/src/resources.js
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
- webapp/src/views/About.vue
Closes #361 
This PR adds the endpoint `/info/stats` for getting some counters about a deployment, and then shows them on the about page in the app, currently just in a very basic table.
To-do:
> Add sample/user/cell counters to deployment about page

- pydatalab/pydatalab/routes/v0_1/collections.py
- webapp/cypress/e2e/batchSampleFeature.cy.js
- webapp/src/views/CollectionPage.vue
- webapp/src/views/EditPage.vue
Closes #329 where the human-readable last modified text would be incorrect by a) fixing the timezone of date comparisons and b) making the value dynamic, updating every 30 seconds.
> Fix last modified timezone and make value dynamic

- README.md
Some magic going on to render this in the README, not sure how it looks in the docs but will have to fix after its deployed...
> Add subtitled intro video to README

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/file_utils.py
- pydatalab/pydatalab/main.py
- webapp/src/file_upload.js
- webapp/src/resources.js
Closes #471 by adding file upload limits:
Also this PR makes the files directory on app startup, if not present. Previously the routes themselves were making it on first upload, potentially with all required subdirectories. This can be a bit dangerous if the files directory is a dynamic mount point, as the wrong disk may silently be used if not previously mounted. We should probably make this more robust in the future, with better specification of e.g. remote data sources too for the files directory (S3 or other blob storage). May be worth abstracting this away with something like Maggma as a "store" controller but equally this may overcomplicate things for little gain for us.
Additionally, in the future/now if easily done, it would be nice to add better feedback on failures in the UI, …
> Adding limits on file uploads

- INSTALL.md
- README.md
- mkdocs.yml
- pydatalab/docs/.pages
- pydatalab/docs/config.md
- pydatalab/pydatalab/config.py
- pydatalab/tasks.py
- webapp/package.json
Refreshes the installation docs and adds significant chunks of docs about
> Revamp installation docs with additional configuration/administration/deployment info

- .docker/server_dockerfile
- .github/workflows/ci.yml
- docker-compose.yml
This should speed up the CI a little bit by using `docker buildx bake` to do cached builds, plus the cypress GH action to avoid needing to install it.
> CI build optimisations

- .github/workflows/ci.yml
Since the last couple of PRs runs have not been uploaded to Cypress cloud. This PR fixes that.
Also its a test to see if the e2e tests really do work in the current state, or whether #484 is really just broken...
> Make sure cypress cloud runs are recorded

- pydatalab/docs/config.md
- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/models/items.py
- pydatalab/tests/routers/test_samples.py
- pydatalab/tests/test_config.py
- webapp/src/components/FormattedRefcode.vue
cc @jdbocarsly 
I initially made this a completely mandatory value but it broke a lot of our testing, so for now it just emits a big warning if unset (and defaults to `test` rather than `grey`).
It also makes the app more robust to other prefixes; we should probably style them differently but that can wait.
> Clarify refcode prefix docs and config

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/logger.py
- pydatalab/pydatalab/main.py
- pydatalab/tests/test_config.py
This PR simply loops over some common secrets and warns on startup if they are not present. At some point we could allow blocks to define these secrets dynamically rather than enumerating in main, but this should help with debugging of deployments.
> Check and warn for missing secrets in server startup logs

- pydatalab/pydatalab/apps/raman/blocks.py
This is the bug I spotted @elbee99, think I introduced it when reviewing your last PR. Thankfully its a simple fix!
> Fix `y_options` bug when plotting 1D Raman

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/logger.py
This PR simplifies the streamed logs (excludes login status) and adds the option for a log dir of rotating files, rather than relying on stdout/docker logs.
> Add rotating file log handler and simplify streamed log messages

- pydatalab/pydatalab/routes/v0_1/items.py
- webapp/src/components/CellInformation.vue
- webapp/src/components/CollectionList.vue
- webapp/src/components/CollectionSelect.vue
- webapp/src/components/CollectionTable.vue
- webapp/src/components/FancyCollectionSampleTable.vue
- webapp/src/components/ItemRelationshipVisualization.vue
- webapp/src/components/SampleInformation.vue
- webapp/src/components/ToggleableCollectionFormGroup.vue
- webapp/src/main.js
- webapp/src/resources.js
This PR adds a `CollectionSelect` to the sample and cell pages that can be used put items into existing collections. This UI was missing from #404 and closes #423. This required a minor specialisation of the existing collections UI to avoid duplicate listed entries in cases where a sample is already in a collection.
Still missing is a way to add items to a collection from the collections page, as this requires more plumbing on the API side.
> Add UI for adding an existing item to an existing collection

- pydatalab/Pipfile
Closes #538.
This PR still uses the pre-release of both navani and galvani, and will need to be updated when they are both released.
> Bump navani to support ECLab <=11.50

- webapp/src/components/Navbar.vue
Quick change to add space above the logo. There is currently no space, which looks odd if the logo .png doesn't have space in it:
> Add spacing above logo

- webapp/src/App.vue
- webapp/src/components/FormattedCollectionName.vue
- webapp/src/components/FormattedItemName.vue
Closes #578 by adding a drop shadow so collections names still give some feedback when hovered over.
> Add drop shadow to badge hover 

- webapp/src/components/LoginDetails.vue
This is confusing on new deployments since we have no instructions for registering an ORCID app.
> Disable ORCID sign-in UI for now

- .prettierrc
- webapp/package.json
- webapp/yarn.lock
Prettier has changed the way it formats code from version-to-version. So, to ensure that the weapp's version of prettier (invoked using `yarn lint`) and pre-commit's don't clash, this pins the version.
Also explicitely specifies `trailingComma: all` in the `.prettierrc` to be explicity about which settings we are using.
> Pin prettier version in Webapp to same version that is specified in pre-commit

- .pre-commit-config.yaml
Related to #589; downgrades pre-commit prettier to use the same version as package.json.
> Downgrade pre-commit prettier

- webapp/src/App.vue
- webapp/src/components/BatchCreateSampleModal.vue
- webapp/src/components/CellPreparationInformation.vue
- webapp/src/components/CollectionRelationshipVisualization.vue
- webapp/src/components/CompactConstituentTable.vue
- webapp/src/components/FormattedCollectionName.vue
- webapp/src/components/FormattedRefcode.vue
- webapp/src/components/ItemGraph.vue
- webapp/src/components/ItemRelationshipVisualization.vue
- webapp/src/components/LoginDetails.vue
- webapp/src/components/MessageBubble.vue
- webapp/src/components/RelationshipVisualization.vue
- webapp/src/components/SampleTable.vue
- webapp/src/components/SynthesisInformation.vue
- webapp/src/components/TableOfContents.vue
- webapp/src/components/ToggleableCollectionFormGroup.vue
- webapp/src/views/CollectionPage.vue
This PR generally cleans up some of our CSS:
> CSS cleanup

- pydatalab/pydatalab/blocks/base.py
Closes #598.
Will be a follow-up PR soon that properly validates block data in both directions.
> Fix issue where plot data was always stored in db

- pydatalab/pydatalab/file_utils.py
- pydatalab/tests/server/test_files.py
Right now, if you upload a file with the same name, it fails simply due to Python attribute access error. We should try to add a test in this PR that verifies this.
Closes #600
> Fix issue where previously uploaded file cannot be replaced

- .docker/app_dockerfile
- .docker/app_entrypoint.sh
- .dockerignore
- .github/workflows/ci.yml
- docker-compose.yml
- webapp/cypress/e2e/editPage.cy.js
- webapp/cypress/e2e/sampleTablePage.cy.js
- webapp/package.json
- webapp/yarn.lock
This is for the production Docker builds, which do not receive these values from `.env` at build time.
Closes #591, in a somewhat satisfactory way, since only deployment related files need to change, and the effect on someone performing a deployment is minimal (they still define things as docker-compose args or as a `.env` file). The only difference now is that the production docker builds will not use the default values (localhost for the API URL, and blank for the other two), and instead will use gibberish values. Probably gibberish is preferable (though the `magic-api-url` could be altered to something more descriptive).
This script and the `Dockerfile` will both need to be updated if we add more `VUE_APP_*` args.
One could argue that all config can actually be dynamically announced by …
> Dynamically set production app container config in entrypoint

- pydatalab/pydatalab/blocks/base.py
Previously the block state stored in the database included any errors and warnings. This should now be reset every time the block is re-rendered.
Closes #611
> Hotfix for block errors and warnings UI that arise over multiple renderings

- webapp/src/components/CellPreparationInformation.vue
- webapp/src/components/CompactConstituentTable.vue
- webapp/src/components/SynthesisInformation.vue
- webapp/src/components/itemCreateModalAddons/CellCreateModalAddon.vue
- webapp/src/components/itemCreateModalAddons/SampleCreateModalAddon.vue
Closes #628 by restricting the types that are searched for in the synthesis/constituents tables.
> Restrict relationship types in UI synthesis and constituents tables

- webapp/src/components/TinyMceInline.vue
Currently, it is not possible to copy or paste from the right click context window in our tinymce fields. Tinymce has a copy/paste functionality, but apparently it is blocked in many browsers. So, the best option for now seems to be to not use tinymce's contextmenu at all, and instead enable the default browser right click.
closes #633
> Allow browser context menu in tinymce fields

- pydatalab/pydatalab/routes/v0_1/info.py
This is for ease-of-use in the Python API.
> Serve the identifier prefix in the `/info` response

- .github/workflows/ci.yml
This is simply an oversight. If the tests pass I will merge.
Sadly I don't think the docker cache is being used during builds anymore, but I don't have the energy or wherewithal to go down that undocumented rabbit hole again.
> Fix typo where CI tests were never run in chrome

- .github/workflows/ci.yml
See #653.
Can undo this when cypress action is released.
> Temporarily disable Firefox tests

- pydatalab/pydatalab/apps/echem/blocks.py
Currently we always try to compute cycle summaries on echem data. This fails when there is no `state` in the data, indicating when a cycle starts/ends. For e.g., linear/sweep voltammetry this data is not available, but we can still easily read the files and make useful plots. This PR simply ignores any errors from the navani summariser (for now) and lets the UI still plot whatever data is available.
Ideally we'd add some error checking in navani itself that handles this in a nicer way.
Closes #664
> Allow echem block to plot non-cyclic data

- pydatalab/pydatalab/models/starting_materials.py
- pydatalab/pydatalab/routes/v0_1/items.py
- pydatalab/schemas/startingmaterial.json
- pydatalab/tests/server/conftest.py
- pydatalab/tests/server/test_startingmaterials.py
- webapp/cypress/e2e/editPage.cy.js
- webapp/cypress/e2e/sampleTablePage.cy.js
- webapp/cypress/support/commands.js
- webapp/src/components/CreateItemModal.vue
- webapp/src/components/FancyStartingMaterialTable.vue
- webapp/src/components/StartingMaterialInformation.vue
- webapp/src/components/StartingMaterialTable.vue
- webapp/src/components/StyledInput.vue
- webapp/src/resources.js
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
- webapp/src/views/Samples.vue
- webapp/src/views/SamplesNext.vue
- webapp/src/views/StartingMaterials.vue
Also closes #648 and closes #654
> Add optional functionality to add starting materials from within the webapp

- pydatalab/pydatalab/apps/echem/blocks.py
- pydatalab/pydatalab/blocks/base.py
- pydatalab/pydatalab/bokeh_plots.py
- webapp/src/store/index.js
This PR converts the cycle summary error from #665 into a warning, and makes sure that such warnings disappear when they are no longer valid in the UI.
This required a bit of manual UI hack, but probably fine for now.
> Improve block warning/error reactivity in the UI

- webapp/cypress/e2e/sampleTablePage.cy.js
(Hopefully) fixes the main flaky e2e test.
The issue appeared to be due to the async nature of cypress commands. We had the following code, where 3 different ItemSelect fields are interacted with by searching and then clicking. 
```js
cy.findByLabelText("(Optional) Copy from existing sample:").type("testBcopy");
cy.get(".vs__dropdown-menu").within(() => {
cy.contains(".badge", "testBcopy").click();
});
cy.findByLabelText("(Optional) Start with constituents:").type("component2");
cy.get(".vs__dropdown-menu").within(() => {
cy.contains(".badge", "component2").click();
});
cy.findByLabelText("(Optional) Start with constituents:").type("component3");
cy.get(".vs__dropdown-menu").within(() => {
cy.contains(".badge", "component3").click();
});
```
However, these within() blocks are apparently …
> Debug flaky e2e tests

- pydatalab/pydatalab/routes/v0_1/items.py
- pydatalab/tests/server/test_samples.py
- pydatalab/tests/server/test_startingmaterials.py
- webapp/cypress/e2e/sampleTablePage.cy.js
- webapp/cypress/support/commands.js
- webapp/src/components/BatchCreateSampleModal.vue
- webapp/src/components/CreateItemModal.vue
- webapp/src/server_fetch_utils.js
Closes #643 by adding an option to generate IDs automatically when creating items. If this option is taken, the generated IDs are the same as the refcode, but without the prefix.
This is an updated version of #650, which had gone stale.
> Add option to generate ID automatically when creating items 

- .codecov.yml
This very annoying feature makes un-coveraged PRs very difficult to review, so let's turn it off for now.
> Disable codecov PR annotations

- pydatalab/Pipfile
- pydatalab/Pipfile.lock
- pydatalab/pydatalab/apps/chat/blocks.py
Whinchat was originally built using an (outdated) openai API. Here, we change to using langchain to interface with openai.
> Convert Whinchat to use langchain 

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/logger.py
- pydatalab/pydatalab/main.py
- pydatalab/pydatalab/mongo.py
- pydatalab/pydatalab/routes/v0_1/info.py
- pydatalab/tests/conftest.py
- pydatalab/tests/server/conftest.py
- pydatalab/tests/server/test_auth.py
- pydatalab/tests/server/test_equipment.py
- pydatalab/tests/server/test_graph.py
- pydatalab/tests/server/test_info_and_health.py
- pydatalab/tests/server/test_samples.py
- pydatalab/tests/server/test_starting_materials.py
- pydatalab/tests/server/test_users.py
- webapp/src/server_fetch_utils.js
As discussed in #203 and #671, this PR begins properly testing authenticated routes and permissions by creating and using fake user accounts during testing. At some point, this could be expanded to the UI tests too.
Closes #203.
We will need to update this at some point once the proper permissions model has been decided upon for equipment and starting materials, as for now I've had to run the inventory/equipment deletion tests with the admin client.
> Use mocked API keys in API tests to fake different authentication scenarios 

- INSTALL.md
- pydatalab/docs/.pages
- pydatalab/docs/config.md
- pydatalab/docs/deployment.md
- pydatalab/docs/schemas/equipment.md
This PR updates the docs with improved sections on:
It also moves around some of the config/installation docs to hopefully make things a bit clearer.
> Significant refactor of deployment docs 

- .gitignore
- pydatalab/pydatalab/errors.py
- pydatalab/pydatalab/login.py
- pydatalab/pydatalab/routes/v0_1/auth.py
- webapp/src/components/EditAccountSettingsModal.vue
- webapp/src/components/LoginDetails.vue
Begins to address #645.
ORCID should now be enabled by default as a login source, when configured via the appropriate environment variables.
Eventually the UI should adapt to not show it as an option when not configured on the server.
For now, the user must still register an account via GitHub, but they can then connect their ORCID and use it for future logins.
Once #674 and #687 are merged, admins will be able to allow users to request an account via ORCID alone.
> Enable ORCID connection by default

- .pre-commit-config.yaml
This PR tweaks the pre-commit CI settings so that they only trigger when you ask in a comment "pre-commit.ci autofix". This should reduce the problems of mergeability checks on draft PRs, and will prevent the constant need for rebasing...
> Only fix PRs with pre-commit CI when asked

- webapp/src/components/EditAccountSettingsModal.vue
- webapp/src/main.js
- webapp/src/server_fetch_utils.js
Closes #695 
I've added a button in "Account Settings" to refresh the user's API key.
There's a warning message indicating that the old key will be deleted.
The key is displayed in the "Account Settings" Modal and disappears once the user closes the Modal.
> Added a way to refresh API Key from Account Settings UI

- pydatalab/pydatalab/mongo.py
#693 updated the users index to fix an issue with uniqueness constraints on contact emails/identities.
This required some modification to the database index for users, which now has slightly different settings. Currently when an existing instance is upgraded, this index creation fails due to a conflicting name. This PR simply drops any existing collection if it is found, then recreates it (as is done for the FTS). We could roll this out more generally to other indices as and when we break them.
> Recreate user index with new settings if already existing

- pydatalab/pydatalab/routes/v0_1/blocks.py
Changes transplanted over from #473.
Refactors the block save function and fixes a bug affecting collection blocks, and makes sure that the block actually exists when it is called.
> Fix for saving collection blocks and error handling for excessively large blocks

- pydatalab/tests/server/test_users.py
Debugging as part of #722, to see if these tests actually behave as I expect right now, where you can use both the admin-authenticated app and user-authenticated app in the same test.
> Update tests for current user

- .pre-commit-config.yaml
Merged #728 too hastily. We need to prevent pre-commit from automatically using prettier-4, which for me seems quite broken.
> Revert pre-commit autoupdate for prettier

- pydatalab/pydatalab/apps/chat/blocks.py
- pydatalab/pydatalab/apps/eis/__init__.py
- pydatalab/pydatalab/apps/nmr/blocks.py
- pydatalab/pydatalab/apps/tga/blocks.py
- pydatalab/pydatalab/blocks/base.py
- webapp/src/components/StyledAnchor.vue
- webapp/src/components/StyledBlockHelp.vue
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
- webapp/src/views/EditPage.vue
Related to #705 & #667 
Add information for each block with popper.js on hover in the “Add a block” dropdown inside the EditPage.
The names in the dropdown are slightly different, as we now use those fetched directly from the models and not those in @resource.js (can be change if needed).
The design of the popper.js window is customizable, so don't hesitate to give me feedback.
> Populating dynamic block-level documentation as UI tooltips

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/models/people.py
- pydatalab/pydatalab/routes/v0_1/auth.py
- pydatalab/tests/server/test_auth.py
This PR updates our account registration workflow so that we can have the following behavior for our supported OAuth providers:
- If a GitHub allowed org is configured, nothing has changed, and a user can register and have their account activated automatically
- If `ORCID_AUTO_ACTIVATE_ACCOUNTS` is enabled, when someone registers via ORCID, their account is automatically activated. Otherwise, an admin must approve it.
- If `EMAIL_DOMAIN_ALLOW_LIST` is configured explicitly to `None`, then any address can automatically register an active account. Otherwise, if configured to `[]`, then no-one can register, and if configured to a set of domains, registration will require admin approval.
The main change here is that ORCID auth will now register an account in the default implementation, rather …
> Make account status on registration be configurable by provider

- pydatalab/pydatalab/login.py
- pydatalab/pydatalab/main.py
- pydatalab/pydatalab/permissions.py
- pydatalab/pydatalab/routes/__init__.py
- pydatalab/pydatalab/routes/v0_1/__init__.py
- pydatalab/pydatalab/routes/v0_1/admin.py
- pydatalab/pydatalab/routes/v0_1/auth.py
- pydatalab/pydatalab/routes/v0_1/blocks.py
- pydatalab/pydatalab/routes/v0_1/collections.py
- pydatalab/pydatalab/routes/v0_1/files.py
- pydatalab/pydatalab/routes/v0_1/graphs.py
- pydatalab/pydatalab/routes/v0_1/healthcheck.py
- pydatalab/pydatalab/routes/v0_1/info.py
- pydatalab/pydatalab/routes/v0_1/items.py
- pydatalab/pydatalab/routes/v0_1/remotes.py
- pydatalab/pydatalab/routes/v0_1/users.py
- pydatalab/tests/server/conftest.py
- pydatalab/tests/server/test_permissions.py
Closes #710 by refactoring all routes around blueprints and introducing some new decorators for permissions based on  `account_status`.
> Consider account status during auth and refactor API around blueprints

- webapp/src/components/EditAccountSettingsModal.vue
- webapp/src/components/UserBubble.vue
This PR tweaks the account settings UI to show the user's avatar (bigger), and dynamically reacts to them setting contact emails (which we should validate at some point). There's also instructions of how to register on gravatar, and some minor style tweaks
> Add gravatar instructions and tweak account settings modal

- webapp/src/components/StyledBlockHelp.vue
- webapp/src/components/StyledBlockInfo.vue
- webapp/src/components/datablocks/CycleBlock.vue
- webapp/src/components/datablocks/DataBlockBase.vue
- webapp/src/components/datablocks/EISBlock.vue
- webapp/src/components/datablocks/MassSpecBlock.vue
- webapp/src/components/datablocks/MediaBlock.vue
- webapp/src/components/datablocks/NMRBlock.vue
- webapp/src/components/datablocks/RamanBlock.vue
- webapp/src/components/datablocks/XRDBlock.vue
This PR extends #719 by adding an info hover to the block title itself, and uses the block info data to populate the `accepted_file_extensions` dynamically.
You can see the tweaks needed on each block for this, which emphasizes the need for a refactor like in #616, which makes a less generic base block that can do e.g., file drop downs.
> Add block help to block title

- docker-compose.yml
- pydatalab/pydatalab/main.py
- pydatalab/pydatalab/routes/__init__.py
- pydatalab/pydatalab/routes/v0_1/__init__.py
This PR fixes an issue that causes the landing page to error (annoying for status pages), and also sets some default locations for files, backups and data directories when performing a production docker-compose build (makes life much simpler when using ansible).
> Fix issue with landing page and tweak default docker-compose deployment

- webapp/src/components/EditAccountSettingsModal.vue
- webapp/src/components/StyledInput.vue
Recent changes to StyledInput in https://github.com/the-grey-group/datalab/pull/706 inadvertently broke the display on the StartingMaterialInformation page by removing the bootstrap form-control class. This PR reverts this change so that `form-control-plaintext` is automatically set on readonly instances of StyledInput, and `form-control` is set on non-readonly instances.
However, this behavior can now be overwritten by directly providing one of these two classes to the StyledInput component, e.g. :
```js
<StyledInput readonly class="form-control">
```
This PR replaces #735.
> Fix StyledInput component (v2)

- .docker/app_dockerfile
- .docker/app_entrypoint.sh
- docker-compose.yml
- pydatalab/pydatalab/config.py
Closes #757
Closes #755 
- Updates the default backup location to a point that is definitely safely mounted (`/tmp/backups/` rather than just `/tmp`).
- Hot patches the API URL setting in the production container build
- Add a new `database_dev` service in docker-compose that doesn't require root access to run (by not mounting at `/data/db`).
> Tweak mount points, production Docker entrypoint and development environment

- pydatalab/pydatalab/routes/v0_1/auth.py
> Default to ORCID ID as display name when ORCID user's name is private

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/remote_filesystems.py
- pydatalab/tests/server/conftest.py
- pydatalab/tests/server/test_remote_filesystems.py
Closes #539.
This PR adds a (manual) database lock so that multiple processes do not try to scrape the same filesystems repeatedly, which is the case in production when there are multiple worker processes running the API.
Still need to add unit tests for this; i.e., manually updating the lock and making sure that stale locks (older than the min cache age) are correctly swept away.
> Add process lock for remote filesystem scraper

- .github/workflows/ci.yml
- docker-compose.yml
- webapp/src/components/FancyStartingMaterialTable.vue
- webapp/src/components/Navbar.vue
- webapp/src/components/StartingMaterialTable.vue
- webapp/src/server_fetch_utils.js
i.e., do not show an error message if the API responds with unauthorized, just return a blank table.
At some point #675 will have to address this properly, as right now there is no longer a concept of anonymous, public samples (this will need to be patched explicitly on the public deployment) but it should be easier to transition from strict to looesr auth rather than the reverse (now that we are spreading).
As a side note, I have now disabled testing mode by default on the dev container, as it is now much more straightforward to do user management locally.
Hopefully this is the final PR before releasing!
Closes #762
> Follow new auth requirements in UI tables

- .pre-commit-config.yaml
This PR (hopefully) fixes two issues with our pre-commit
1. The `generate-schemas` hook used `repo:local` and `language:python`, which allows it to run code within our pipenv. However, this means that if `pre-commit` is ever run from outside the pydatalab virtual environment, it will instead attempt to run the code in the system environment, and fail. This can happen if, for example, the user tries to run `git commit` without being in the pydatalab pipenv shell or typing `pipenv run git commit`. The change here uses the `language:system` option and a bash one-liner to manually ensure that `generate-schemas` is always run in the correct `pipenv`. 
3. Recently mypy started breaking with the mysterious `AssertionError: Internal error: unresolved placeholder type None`. This seems to be …
> Changes to pre-commit 

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/main.py
- pydatalab/pydatalab/routes/v0_1/info.py
- pydatalab/tests/server/test_info_and_health.py
- webapp/src/components/LoginDetails.vue
- webapp/src/components/UserTable.vue
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
- webapp/src/views/About.vue
to e.g., disable unconfigured login mechanisms, and more in future.
This PR also tidies up the login details slightly, preventing duplicated calls to `/get-current-user` when not rendering the account settings block.
> Report runtime server config at `/info` and use this in UI

- docker-compose.yml
This PR updates the restart policy for the services in the compose file to `unless-stopped`, which prevents them from clashing and attempting to restart after a reboot (or docker daemon restart).
> Change docker compose restart policy to "unless-stopped"

- webapp/src/components/Navbar.vue
Bit of an inline CSS hack, but closes #798
> Fix logo link taking full screen width

- pydatalab/pydatalab/routes/v0_1/items.py
- pydatalab/tests/server/test_samples.py
- webapp/cypress/e2e/batchSampleFeature.cy.js
- webapp/src/components/BatchCreateItemModal.vue
- webapp/src/components/FormattedItemName.vue
- webapp/src/components/ItemSelect.vue
- webapp/src/components/SampleTablePrime.vue
- webapp/src/views/Samples.vue
- webapp/src/views/SamplesNext.vue
Currently, the "batch add" feature only allows for adding samples. This PR adds the ability to also add cells, with a template option for positive electrode, electroylte, and negative electrode.
Closes #396
> Add ability to add batch of cells

- pydatalab/pydatalab/config.py
- pydatalab/pydatalab/routes/v0_1/auth.py
This brings the three auth mechanisms into parity, and can be helpful for e.g., the demo deployment.
> Add config options to automatically activate accounts from GitHub, email or any auth source

- pydatalab/pydatalab/permissions.py
- pydatalab/pydatalab/routes/v0_1/items.py
- pydatalab/tests/server/conftest.py
- pydatalab/tests/server/test_items.py
- pydatalab/tests/server/test_users.py
First steps on #803 
~This PR adds `/items/by-refcode/<refcode>` and `/items/by-id/<id>` endpoints that essentially replace `/get_item_data/<item_id>`. I'm not entirely happy with the routes yet, and would like to find some examples of how other APIs deal with what are essentially multiple canonical IDs. Having `by-id` and `by-refcode` feels natural, but perhaps simply `/items/refcode/<refcode>` is more extensible and compatible with e.g. JSON:API to other fields in the future.~
Went with this in the end: having `/items/<refcode>` be the canonical URL is appealing, with the "legacy" endpoint being the only way to refer to items by item ID -- this would also allow us to promote refcode at some point to simply be the top-level `id` field in JSON:API parlance, which has some nice properties.
> Add routes for resolving items by refcode

- .github/workflows/ci.yml
- pydatalab/pydatalab/apps/tga/blocks.py
- pydatalab/pydatalab/bokeh_plots.py
- pydatalab/tests/apps/test_tga.py
I've been encountering block issues with an unknown theme option `"major/minor_label_text_font"` that prevents blocks that use the grid plot from being created. There is no mention of these options anywhere in the Bokeh github repo history, which is perplexing, and they were added long enough ago that I guess we should have seen issues before now, especially as we have not updated bokeh for a little while.
> Fix block errors caused by seemingly defunct theme options in bokeh 

- pydatalab/Pipfile
- pydatalab/Pipfile.lock
- pydatalab/pydatalab/apps/echem/blocks.py
Closes #839 with a hotfix, will need to be solved more generally in the future.
> Reload echem data by default, unless disabled

- .docker/server_dockerfile
- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- docker-compose.yml
- Attempt to set `record: false` in cypress CI if running from a fork
- Separate docker build into its own job, shared by all e2e test runners
> CI build time and fork compatibility improvements

- .github/workflows/ci.yml
Follow-up from #833. Adjust the caching strategy by lumping prod builds with e2e tests so that the cache gets used between runs, but not within them.
> Tweak cache usage on docker builds

- .github/dependabot.yml
Now that we are relatively up to date, this PR re-enables dependabot, to see how it deals with the conflicting pipenv/pyproject/requirements file definitions. We may need to turn it off again pretty quickly.
> Re-enable dependabot for Python dependencies

- .docker/server_dockerfile
- .github/workflows/ci.yml
- INSTALL.md
- docker-compose.yml
- pydatalab/docs/config.md
- pydatalab/mkdocs.yml
- pydatalab/pydatalab/main.py
- pydatalab/pyproject.toml
- pydatalab/tests/test_version.py
The setup-tools-scm version was not being picked up outside of docker as the `.git` folder is one level up. This PR fixes that, adds a simple test, and also makes some docs formatting fixes.
> Fix docs formatting and update versioning scheme

- .github/workflows/ci.yml
- .pre-commit-config.yaml
This should be the final step following #582, which strips pipenv from the CI.
We could consider adding a new job that also ensures the pipenv lock is consistent, but this can easily be done manually for now (and is tested indirectly by the `api_dev` docker build which uses `pipenv` for this reason).
> Use uv and deps lockfiles in CI & pre-commit

- .github/dependabot.yml
After this PR, ideally, dependabot will keep ticking over and updating our lock files with the latest versions compatible with our pyproject.toml.
There will then be a second job that lets us know of new major incompatible versions; we can treat these on a case-by-case basis and roll the changes out ourselves, based on the dependabot PRs.
I am hoping the dependabot config is flexible enough for this, otherwise we will have to rewrite lots of the constraints from our pyproject into the dependabot config file, for now.
Dependabot groups are also magic to me, my guess is that for the `pip` ecosystem, any dependency under the extra `dev` is treated as development, and all the rest are production, but thats not entirely clear to me yet (and its not documented).
> Attempt to configure lockfile-only dependabot strategy

- .github/dependabot.yml
It seems that this is still slightly in flux, and we are unable to use multiple workflows per packaging ecosystem. This PR mostly undoes #853 and switches to purely lockfile only updates, avoiding the need for us to pin so heavily in the dependabot config file.
> Re-attempt to use lockfile-only strategy with dependabot

- .docker/app_dockerfile
- .github/workflows/ci.yml
- .pre-commit-config.yaml
Some deps now need node v20+, which we have always recommended anyway. This PR updates our docker, CI and dev envs to use node 20.
> Use node v20 in build, CI and dev environments

- webapp/.eslintrc.js
This PR converts all prettier errors, and some vue errors, into warnings when running in development mode.
> Let linting settings reflect development usage

- pydatalab/pydatalab/apps/chat/blocks.py
Closes #834.
gpt-3.5-turbo are being turned off next month. This PR removes them from the chatblock, but allows old chats to default to the new default model.
Still need to do some local testing.
> Deprecate gpt-3.5-turbo series and handle missing models in chatblock

- pydatalab/pydatalab/apps/chat/blocks.py
> Filter out b64-encoded data before sending to LLM

- .docker/app_dockerfile
- .docker/app_entrypoint.sh
- docker-compose.yml
Some of the new VUE_APP settings are not being deployed properly given our convoluted environment procedure for app settings (which hopefully we can fix in a smarter way with runtime options...)
This PR temporarily fixes that.
> Fix deployment config options for new VUE_APP settings

- .gitignore
- INSTALL.md
- pydatalab/Pipfile
- pydatalab/Pipfile.lock
- pydatalab/pyproject.toml
- pydatalab/scripts/pipenv-resync.sh
- pydatalab/uv.lock
This PR does the following:
- begin migration to a uv-specific lockfile (`uv.lock`), pending its standardisation (we will keep using requirements files for the time being too)
- update Pipfile.lock to have the same values as the requirements
- add script to do this automatically in the future
This sees us basically move to a `Pipfile`-less setup.
> Lockfile compatibility

- webapp/src/components/QRCode.vue
I messed up in #808 and missed an if statement for when to show the alert with info about the federation resolver. This PR fixes that.
> Fix QR code warning showing when not required

- webapp/cypress/component/CreatorsTest.cy.jsx
- webapp/cypress/component/FormattedItemNameTest.cy.jsx
- webapp/cypress/component/NavbarTest.cy.jsx
- webapp/cypress/component/NotificationDotTest.cy.jsx
- webapp/cypress/component/StyledBlockHelpTest.cy.jsx
- webapp/cypress/component/StyledBlockInfoTest.cy.jsx
- webapp/cypress/component/UserBubbleLoginTest.cy.jsx
- webapp/cypress/component/UserBubbleTest.cy.jsx
- webapp/cypress/support/component-index.html
- webapp/src/components/NotificationDot.vue
- webapp/src/components/StyledBlockHelp.vue
- webapp/src/components/StyledBlockInfo.vue
Related to #794
I've started writing tests on some components, trying to test as many things as possible. Feedback welcome.
Components covered by test:
- NotificationDot
- UserBubble
- UserBubbleLogin (It's just UserBubble with NotificationDot, so maybe doesn't need so much tests)
- Navbar
- StyledBlockInfo
- StyledBlockHelp
- FormattedItemName
> Add component tests 

- webapp/src/components/CollectionSelect.vue
- webapp/src/components/DynamicDataTable.vue
> Fix some issues in the datatable

- webapp/cypress/e2e/sampleTablePage.cy.js
- webapp/cypress/support/commands.js
- webapp/src/components/AddToCollectionModal.vue
- webapp/src/components/CollectionInformation.vue
- webapp/src/components/CollectionTable.vue
- webapp/src/components/DynamicButtonDataTable.vue
- webapp/src/components/DynamicDataTable.vue
Closes #815
Closes #891.
Replaces the next table on collections with the new dynamic table, and:
> Add dynamic data table on collection page

- webapp/src/components/datablocks/DataBlockBase.vue
Closes #838
Add collapsible functionality for block warnings
> Add Collapsible Functionality for Block Warnings

- .github/dependabot.yml
c.f. #864 and #848 -- this PR excludes pydantic from the dependabot config so that other compatible deps can update without issue.
> Exclude pydantic from dependabot

- pydatalab/pyproject.toml
- pydatalab/requirements/requirements-all-dev.txt
- pydatalab/requirements/requirements-all.txt
- pydatalab/uv.lock
This PR moves more deps to 'core', which was previously unused. I think this may help dependabot figure out which deps need to be installed alongside each other.
This PR also updates navani to 0.1.7, which includes important fixes for Neware.
> Rearrange dependencies and update navani

- .github/dependabot.yml
Dependabot simply can't cope with our repo and fails to even attempt to obey any versioning constraints. This PR re-enables lockfile only mode, which should at least explicitly ignore versions not allowed by `pyproject.toml` rules.
Probably once we have fully migrated we should roll our own scheduled `uv lock -U` action for our Python deps, and leave dependabot for security updates in npm only, or wait for better explicit `uv` support in dependabot (https://github.com/dependabot/dependabot-core/issues/10478)
> Re-enable lockfile only mode of dependabot

- webapp/cypress/e2e/batchSampleFeature.cy.js
- webapp/cypress/e2e/equipment.cy.js
- webapp/cypress/e2e/sampleTablePage.cy.js
- webapp/cypress/support/commands.js
- webapp/src/components/DynamicButtonDataTable.vue
- webapp/src/components/DynamicDataTable.vue
- webapp/src/components/DynamicDataTableButtons.vue
Closes #897 
This PR refactors the "Add to Collection" and "Delete Selected" actions into a PrimeVue SplitButton dropdown.
Also add a small fix to make cypress e2e tests work with dropdown.
> Add dropdown with actions buttons for selected items inside DataTable

- webapp/src/components/BatchCreateItemModal.vue
- webapp/src/components/CollectionSelect.vue
- webapp/src/components/CreateCollectionModal.vue
- webapp/src/components/CreateEquipmentModal.vue
- webapp/src/components/CreateItemModal.vue
- webapp/src/field_utils.js
Closes #890
- Creation of a new utility function for ID validation inside field_utils.js
- Replacement of duplicate validation logic in modals with calls to the new utility function.
> Refactor ID Validation Logic into Utility Function

- .docker/server_dockerfile
In #914 we switched to a non-editable install inside the docker containers, which means that datalab runs from the installed module (`/opt/.venv/lib/python3.10/site-packages/...` etc), but the dotenv loader only looks in that folder and above (rather than the datalab source folder).
Long term, 
but short-term, we can just got back to an editable install (makes no difference inside the container) so that the current deployment `.env` path is still found.
> Install datalab as editable inside docker build to make env passing simpler

- webapp/src/components/DynamicDataTable.vue
Related to #889
Fix css issues applied to primevue components after adding 'scoped' to styles
Also removes padding in the datatable
> Fix css issues in DynamicDataTable

- pydatalab/src/pydatalab/routes/v0_1/collections.py
- pydatalab/tests/server/test_samples.py
Previously, when creating a collection the `immutable_id` is returned as `None`, as we do not set the database-assigned ID back to the creation model. As collection relationships work from this ID, it is very helpful to return it, so that another request to `get_collection` does not need to be made to get the ID (see https://github.com/datalab-org/datalab-api/pull/35) for the required Python API workaround for this).
> Ensure that new collection `immutable_id` is returned upon creation

- .docker/app_dockerfile
- .docker/server_dockerfile
- .github/workflows/ci.yml
- docker-compose.yml
- pydatalab/src/pydatalab/main.py
Previously, the docker-based dev server implicitly called `load_dotenv` to load any environment variables into global state, as part of `flask run`. Since the dev containers have now been removed, it is useful to be able to control a few select env vars in this way through the gunicorn-based container.
This PR hardcodes the setting of `OAUTHLIB_INSECURE_TRANSPORT` as an env var, when specified in the `.env` file. This allows OAuth login to be used locally without https.
> Explcitly set `OAUTHLIB_INSECURE_TRANSPORT` env var when present in `.env`

- .github/workflows/ci.yml
- pydatalab/pyproject.toml
Codecov uploads have been failing since #865, as the coverage directory is now incorrect. Hopefully this fixes that.
> Configure coverage for new src-layout

- .docker/app_dockerfile
- .docker/app_entrypoint.sh
- .docker/server_dockerfile
- docker-compose.yml
This PR follows up #906 by using the version in the docker build, where available. It also provides the ability to manually set the tag version (useful in cases where the docker build is running inside git worktrees, or submodules).
> Use git version inside app container build

- webapp/package.json
- webapp/src/components/datablocks/DataBlockBase.vue
- webapp/src/components/datablocks/NotImplementedBlock.vue
- webapp/src/views/EditPage.vue
- webapp/yarn.lock
Should remove the annoying warning when doing block development.
Also prevents reloading the block info endpoint for every edit page.
> Better handle case where block in database is not implemented by app/API

- pydatalab/src/pydatalab/routes/v0_1/collections.py
- pydatalab/tests/server/test_samples.py
Closes #932.
This also provides a template for #543, which we should really use everywhere throughout the API for routes that make multiple database calls
> Update collection deletion endpoint to also unlink items

- webapp/src/components/DynamicDataTable.vue
- webapp/src/main.js
- webapp/src/primevue-theme-preset.js
Setting up a custom theme for primevue instead of applying global css to primevue components 
- Set transition time to 0.05s (default: 0.2s)
- Set the padding of datatable headers and cells to 0.5rem (default: offset between header and bodycell)
- Hides the sorting icon until the header is hovered
- Make the text in the cells appear on a single line (nowrap and overflow hidden)
- Make the filter icon change color when a filter is active
- Checkboxes color grey
> Set up custom primevue theme

- webapp/src/server_fetch_utils.js
- webapp/src/views/EditPage.vue
Closes #926.
This one is my bad; in #808 I refactored the edit page to also be able to load from refcodes, so the code went from a single method with a promise handler to do the rest of the loading, to an if/else choosing between two async methods, with the rest of the loading happening outside of the promise, i.e., immediately (before the data had loaded).
This PR fixes that and refactors block loading into its own method. It also hides some components until the block info and item data is fully loaded.
Long story short, we need a test for this edit page behaviour (I will endeavour to make one)!
> Fix bug where blocks would not be loaded automatically

- webapp/src/views/EditPage.vue
Related to #935, for some reason that I can't quite discern, adding an `isItemLoaded` guard to displaying the file list prevents uppy from being loaded properly. I've removed that guard and tweaked the unloaded value of `item_data` to be `{}` so that key access simply fail and return `undefined`, rather than erroring out.
> Tweak for edit page to allow upload file modal to load correctly

- webapp/src/file_upload.js
Do not consider filenames when uploading a file via uppy, just show the alert
Closes #939
> Hotfix for file-overwriting from uppy

- .github/workflows/dependable-bot.yml
dependabot is not being very useful right now. Instead, I propose a simple wf that runs `uv lock -U` each week and makes a PR with any changes, similar to a grouped dependabot update PR that should always lead to latest compatible versions.
We could then adapt this in the future with updates for newer (potentially breaking) versions of other deps.
If this works, we can disable dependabot for Python for all but security updates (which I don't believe `uv` has explicit support for), and leave it on only for `npm`.
> Add scheduled `uv lock -U` to replace dependabot

- .github/dependabot.yml
- .github/workflows/dependable-bot.yml
- pydatalab/pyproject.toml
- pydatalab/uv.lock
The first iteration of this workflow opened #946, which included the output.txt file and was poorly labelled.
This PR fixes that, and after merging, re-running the workflow manually should lead to the PR being recreated.
> Tidy up uv workflow after first generated PR

- .github/workflows/ci.yml
- .github/workflows/dependable-bot.yml
Long story short: checks won't run on PRs created by actions, like #945 (see long history at https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-1411863193 for why)
The suggested workaround is to always make the PRs as drafts, then have the tests trigger when someone clicks `ready-for-review`. If this works, it seems fairly elegant to me. This PR implements that, and I will merge it straight away to test.
> Add suggested 'ready-for-review' workaround to checks not running from actions-created PRs

- webapp/cypress/e2e/editPage.cy.js
- webapp/cypress/fixtures/example_data
- webapp/cypress/support/commands.js
This PR extracts just the tests from #938 before the refactor in #943.
> Add e2e JS tests for file upload and block creation

- .docker/app_dockerfile
After talking to my esteemed colleague Claude, I now realise that `yarn install` includes dev dependencies by default. By splitting our docker build into two stages, one that uses all deps to make the build, and the next that only installs runtime deps, combined with #957 I can shave ~ 1 GB off the final image size.
> Split vue docker build into two stages

- .github/workflows/dependable-bot.yml
- .github/workflows/yarn-upgrade-bot.yml
Reduces updates frequency of `yarn.lock` and `uv.lock` to once a week (during the night from Tuesday to Wednesday)
> Reduces updates frequency to once a week

- .github/workflows/dependable-bot.yml
- .github/workflows/yarn-upgrade-bot.yml
I think it makes sense to stagger the Python/JS ecosystem updates, so if we have any issues in the week after merging one, we can be fairly sure it was the cause. This PR staggers the updates so that Python updates on Wednesdays in the 1st and 3rd week of a month, and JS in the 2nd and 4th.
> Stagger fortnightly scheduled uv/yarn updates

- pydatalab/pyproject.toml
- pydatalab/schemas/cell.json
- pydatalab/schemas/equipment.json
- pydatalab/schemas/sample.json
- pydatalab/schemas/startingmaterial.json
- pydatalab/scripts/migrate_files_to_files_ObjectId_v2.py
- pydatalab/src/pydatalab/backups.py
- pydatalab/src/pydatalab/file_utils.py
- pydatalab/src/pydatalab/models/files.py
- pydatalab/src/pydatalab/models/utils.py
- pydatalab/src/pydatalab/remote_filesystems.py
- pydatalab/src/pydatalab/routes/v0_1/auth.py
- pydatalab/src/pydatalab/routes/v0_1/collections.py
- pydatalab/src/pydatalab/routes/v0_1/items.py
- pydatalab/tests/server/test_equipment.py
- pydatalab/tests/server/test_remote_filesystems.py
- pydatalab/tests/server/test_samples.py
- pydatalab/tests/server/test_starting_materials.py
- pydatalab/tests/test_models.py
- webapp/cypress/e2e/equipment.cy.js
- webapp/src/components/StartingMaterialInformation.vue
- webapp/src/field_utils.js
- webapp/src/resources.js
- webapp/src/views/CollectionPage.vue
- webapp/src/views/EditPage.vue
This PR enforces UTC for all datetimes stored by datalab, via:
- updating the underlying model so that any missing timezone from a user/script is interpreted as UTC. This is done at the validator level, so some inconsistencies might arise in old data that has not previously been stored with a timezone, but the API at least will always validate and fix it this now. I explicitly added the timezones into remote fs checking so that we don't have to worry about mongo version compatibility.
- The app code can now assume that a missing timezone really does mean UTC, and all future timestamps should have the `00:00` UTC offset suffix.
- App code now has to have a custom computed setter/getter for datetime objects, so that we can cast the format from HTML `<input format='datetime-local'>` into the …
> Add timezone consistency across deployments & UI

- pydatalab/src/pydatalab/apps/chat/blocks.py
- pydatalab/src/pydatalab/main.py
Previously, LLM API keys were automatically set as env vars by pipenv as part of the build process. In this PR, the procedure is passed onto flask itself.
> Chatblock deployment fix: make sure LLM API keys are passed from .env to environ

- webapp/vue.config.js
In our build, we are getting a warning about the fact that we don't have a polyfill for one of cypress's subdependencies, which uses the node.js `vm` function:
``` 
warning  in ./node_modules/asn1.js/lib/asn1/api.js
Module not found: Error: Can't resolve 'vm' in '/Users/josh/datalabvue/webapp/node_modules/asn1.js/lib/asn1'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "vm": require.resolve("vm-browserify") }'
- install 'vm-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "vm": false }
```
I don't believe we …
> Explicitly don't use a polyfill for `vm`

- .github/workflows/dependable-bot.yml
- .github/workflows/yarn-upgrade-bot.yml
GitHub Actions schedules convert `day (month)` && `day (week)` clauses in cron jobs as `OR`, so we were just running every day of the week. This PR goes back to the simple case where both upgrade PRs run on a Wednesday. We can always just close the PR one week if we don't want to deal with it.
> Revert overly smart schedule for upgrade PRs

- pydatalab/schemas/cell.json
- pydatalab/schemas/equipment.json
- pydatalab/schemas/sample.json
- pydatalab/schemas/startingmaterial.json
- pydatalab/src/pydatalab/models/entries.py
- pydatalab/src/pydatalab/mongo.py
- pydatalab/tests/server/test_items.py
Closes #997, and is related to #993
This PR improves how we choose which fields to use in the FTS.
Previously, some IDs were being included, which will no longer happen.
Also, some field names were being added by aliases that are not present in the database, so were excluded (mostly starting materials fields).
> Fix and refactor FTS field generation

- .docker/server_dockerfile
- docker-compose.yml
Right now, if the version of datalab is being installed from a git submodule, or a worktree, it is impossible to set the API version. For the app, we can override  this with the `VUE_APP_GIT_VERSION`. For the API, we have to use the `SETUPTOOLS_SCM_PRETEND_SCM_VERSION`. This PR passes that value through the build system to make it available when `uv` installs.
> Add docker build var to spoof API version

- webapp/cypress/e2e/batchSampleFeature.cy.js
- webapp/src/components/BatchCreateItemModal.vue
- webapp/src/components/StatisticsTable.vue
- webapp/src/views/About.vue
Add missing `<tbody>` or `<tr>` inside `components/BatchCreateItemModal.vue`, `components/StatisticsTable.vue` & `views/About.vue`
> Fix vue-loader errors

- webapp/cypress/component/NavbarTest.cy.jsx
- webapp/src/components/Navbar.vue
Fix the alignment of LoginDetails when an unverified user is logged in
> LoginDetails alignment when a user is unverified

- .github/workflows/ci.yml
- docker-compose.yml
- Remove annoying warning by removing default value for spoof version in docker-compose
- Add version spoof to CI to check that it does not introduce build failure
> Tweak git version spoofing in docker config, and test it 

- webapp/src/components/DynamicDataTable.vue
- webapp/src/primevue-theme-preset.js
This PR attempts to turn on resizable columns and set the starting size with `"fit"`, addressing #889,
It also then tries to use a custom enum filtering for item types. For now, I just pull the values that the user has in the table, but ideally in the future it would query the server for the API schemas to see which types are available globally.
This doesn't quite work yet, the filtering does not seem to be applied correctly for types. Could oyu maybe take a look @BenjaminCharmes?
> Dynamic table tweaks: filter by item type enum & resizable columns

- webapp/src/views/EditPage.vue
This will preserve the store when going back and forth betweens samples via the home button.
I think more generally, we can now think of more aggressively caching table data to speed-up load times, i.e., on table load, first just check the store and use that value if its not empty. Potentially an async load could then be triggered in the background (related to https://github.com/datalab-org/datalab/pull/1013#pullrequestreview-2468184726).
> Use `<router-link>` for "Home" button on edit page to preserve store

- pydatalab/src/pydatalab/routes/v0_1/items.py
- pydatalab/tests/server/test_permissions.py
- webapp/cypress/e2e/editPage.cy.js
- webapp/src/components/CellInformation.vue
- webapp/src/components/Creators.vue
- webapp/src/components/DynamicDataTable.vue
- webapp/src/components/SampleInformation.vue
- webapp/src/components/ToggleableCreatorsFormGroup.vue
- webapp/src/components/UserSelect.vue
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
- webapp/src/views/EditPage.vue
This PR adds a user select and toggleable editable option to the creator list for items.
It should prevent the user from removing themselves, and should potentially prevent the user from removing other people (i.e. append-only share), or some more tortured logic where the "first" creator in the list takes precedence.
This also adds a new API route `PATCH /items/<refcode>/permissions` for this use case, with some tests.
Works similarly to the toggleable collection block, except that API call is made when the editing state is completed, and has a confirmation dialog.
Some outstanding things (for this PR or otherwise):
> User select and sharing of sample page with creators

- pydatalab/src/pydatalab/permissions.py
- pydatalab/src/pydatalab/routes/v0_1/collections.py
- pydatalab/src/pydatalab/routes/v0_1/items.py
- pydatalab/tests/server/test_starting_materials.py
- webapp/src/server_fetch_utils.js
like equipment and starting materials. Probably these should not be deletable, until we configure them to be tied to a certain user on creation (related to #835 and #831).
> Carve out exception for delete permission for group-wide items

- pydatalab/src/pydatalab/routes/v0_1/items.py
Closes #1000 by adding `blocktypes` in the sample summary responses, wanted to sneak this in before the release!
> Add block types and titles to summary API response

- .docker/server_dockerfile
- .github/workflows/ci.yml
- pydatalab/uv.lock
This was causing some issues with later versions in the 0.4.x stream of `uv`.
Developers can update their own `uv` installations with `uv self update`.
> Update uv to 0.5.x now that dynamic versioning is supported

- pydatalab/mkdocs.yml
This should redirect anyway but we may as well use the real link.
> Fix docs link in mkdocs

- webapp/src/router/index.js
- webapp/src/views/Login.vue
- webapp/src/views/Login2.vue
- webapp/src/views/Login3.vue
Closes #767 
- Login splash screen that displays the login options (GitHub, ORCID, and email)
- Updated route handling to redirect unauthenticated users to the /login page, with the exception of the /about page, which remains accessible without authentication.
> Add Login Splash Screen

- webapp/src/components/DynamicDataTableButtons.vue
Closes #944
Add an overlay while deleting multiple items to prevents the user from interrupting the process.
> Add overlay while deleting multiple items

- pydatalab/pyproject.toml
- pydatalab/uv.lock
pymongo 4.11 only supports MongoDB 4+, and we are quite behind in our MongoDB updates (see #814). This PR is a temporary fix.
> Add upper pin to pymongo

- pydatalab/src/pydatalab/routes/v0_1/items.py
- pydatalab/tests/server/test_samples.py
After noodling around in #993, I think the conclusion is that its not worth maintaining a potentially large separate custom index for FTS that works with only a few characters. Instead, as a bit of a prototype, this PR adds a simple regex-based search that can triggered in the item select by prefixing the query with "%". This seems to work fairly well at our typical database sizes, but might need some optimisations. For now it also only uses the fields that are currently part of the free-text index, but this could be expanded (and we can add real indices over these fields if performance is bad).
Closes #679?
> Add regex-based alternative to full-text search

- webapp/src/views/EditPage.vue
Simple fix to prevent the annoying bug where the unsaved warning erroneously appears whenever a sample or cell page is loaded a second time without a refresh.
closes #601
> Reset unsaved warning after `getSampleData()` receives data

- webapp/src/components/SampleTable.vue
Closes #1047 
This PR fixes the sorting issue for both `Collections` and `Creators` in the PrimeVue DataTable by ensuring that a list of strings is passed as props instead of arrays of objects.
> Fix Datatable sorting for Collections and Creators

- webapp/src/components/BaseIconCounter.vue
Tone down the red circles and replace it with an underline, to attempt to indicate that you can still hover
> Adjust block and file counter style

- pydatalab/pyproject.toml
- pydatalab/src/pydatalab/apps/chat/blocks.py
- pydatalab/src/pydatalab/apps/echem/blocks.py
- pydatalab/src/pydatalab/apps/nmr/utils.py
- pydatalab/src/pydatalab/backups.py
- pydatalab/src/pydatalab/blocks/base.py
- pydatalab/src/pydatalab/config.py
- pydatalab/src/pydatalab/file_utils.py
- pydatalab/src/pydatalab/logger.py
- pydatalab/src/pydatalab/models/utils.py
- pydatalab/src/pydatalab/mongo.py
- pydatalab/src/pydatalab/remote_filesystems.py
- pydatalab/src/pydatalab/routes/v0_1/auth.py
- pydatalab/src/pydatalab/routes/v0_1/items.py
- pydatalab/tasks.py
- pydatalab/tests/server/conftest.py
- pydatalab/tests/server/test_equipment.py
- pydatalab/tests/server/test_files.py
- pydatalab/tests/server/test_remote_filesystems.py
- pydatalab/tests/server/test_samples.py
- pydatalab/tests/server/test_starting_materials.py
- pydatalab/tests/test_config.py
- pydatalab/uv.lock
Closes #1115
This (ongoing) work uncovered some bugs:
> Treat warnings in pytest as errors, fixing things along the way

- pydatalab/src/pydatalab/routes/v0_1/items.py
Closes #1130, fairly urgently. This had not been deployed anywhere but is a bit nasty in terms of allowing users to search for other user's samples.
This could be avoided in the future by wrapping all database access in a class that injects permissions at the top level, though this is only worth doing once the new permissions system is in.
I'll merge this myself once the tests pass.
> Fix oversharing regex search

- pydatalab/src/pydatalab/blocks/common.py
- webapp/src/components/datablocks/MediaBlock.vue
This was way easier than I expected just using an iframe (rather than having to bundle e.g., PDF.js and the like). Will be useful for e.g., #658
> Add PDF support in MediaBlock using an iframe

- webapp/src/components/DynamicDataTable.vue
- webapp/src/primevue-theme-preset.js
Closes #1108 
The numbers always appear when you're in `sort-mode="multiple"` and prime-vue only removes them when you're in `sort-mode="single"`. This allows the user to know that they can sort several columns at once.
I guess we can find a way of removing the "1" when only one column is sorted, but I couldn't find anything in the prime-vue docs, or even using the custom theme we have in datalab (the two columns have exactly the same css classes), so I had to add another custom css class.
It's a first attempt to see what it could be.
> Remove datatable-sort-badge when only one column is sorted

- webapp/src/views/EditPage.vue
I think one of the errors I see in development a lot has just come up during #1133 -- if a block tries to access its schema when loading (to e.g., get accepted file extensions), then this can sometimes fail if the store is not ready. This PR simply adds the existing guard for whether block schemas have been loaded before loading the block list itself. At some point we should refactor the store to do a lot of this stuff automatically.
> Add guard for block info loading to edit page

- webapp/src/components/StartingMaterialInformation.vue
Locations can be quite long, so let's give them more space.
> Give starting material location its own row in the UI

- webapp/src/components/DynamicDataTable.vue
> Multiselect filtering for "no values" in nblocks column

- docker-compose.yml
Previously it was impossible to set e.g., `WEB_CONCURRENCY` at anything but the default value, as the it would be overridden by the compose file value.
> Allow runtime compose args to be set from environment variables

- pydatalab/src/pydatalab/routes/v0_1/items.py
I accidentally depended on an item having `files` saved in the db, where actually it should only be a field constructed for the API response. This crept through as calling `save-item` from the app included this field, and as it fits the pydantic model, it was being saved in the database.
We still need a better way of distinguishing such fields between the database and API, by adding special validators to the base entry types and annotating them as such in our models, but this just patches this problem for now.
> Do not update 'files' reference when saving item

- pydatalab/uv.lock
This PR updates some choice deps in the `uv.lock`:
- flask and related packages
- dask, httpx, jinja2 and pydantic (still within v1)
- newarenda
> Updating several dependencies in `uv.lock`

- webapp/src/components/CollectionTable.vue
- webapp/src/components/DynamicDataTable.vue
- webapp/src/components/EquipmentTable.vue
- webapp/src/components/SampleTable.vue
- webapp/src/components/StartingMaterialTable.vue
- webapp/src/primevue-theme-preset.js
- webapp/src/server_fetch_utils.js
- webapp/src/store/index.js
Closes #1194.
@BenjaminCharmes could you take a look at rolling this out across all item types? I don't think we necessarily need to make everything async for this work, but it should be straightforward to default to `null` in the store when things are loading and `[]` when they are actually empty.
As a side issue, the visual template for loading isn't particularly nice (grey overlay across entire component, with white text... perhaps this could be improved here too).
> Set DataTable loading state when loading from store

- pydatalab/README.md
- pydatalab/pyproject.toml
- pydatalab/uv.lock
Closes #1208.
Also fixes the minimum setuptools version, and properly passes the README to the PyPI build process.
> Use `tool.uv.sources` to specify in situ plugin git dependency in pyproject

- pydatalab/pyproject.toml
- pydatalab/src/pydatalab/apps/__init__.py
- pydatalab/src/pydatalab/apps/_canary/__init__.py
- pydatalab/src/pydatalab/blocks/__init__.py
- pydatalab/src/pydatalab/blocks/base.py
- pydatalab/src/pydatalab/blocks/common.py
- pydatalab/src/pydatalab/routes/v0_1/blocks.py
- pydatalab/src/pydatalab/routes/v0_1/info.py
- pydatalab/src/pydatalab/routes/v0_1/items.py
- pydatalab/tests/apps/test_plugins.py
- pydatalab/uv.lock
Closes #1178 by moving all block loading into the apps module.
This still feels like a bit of a temporary solution, ideally this could be refactored away at some point with better hierarchy between apps and blocks, but for now this is the way of doing it with minimal server import changes (otherwise we'd have to move the base data block and change every block and plugin to use a new location of base data block). The overall problem stems from the fact that the base block is implemented in `pydatalab.blocks.base` and we want to import it, and many child classes of it, from the top-level `pydatalab.blocks`. This PR simply moves the loading stage into `pydatalab.apps`.
Also makes pymongo a core dep.
Relatedly we should also worry about https://github.com/datalab-org/datalab/issues/1159 -- …
> Refactor app block loading to prevent optional dependencies from breaking dev builds

- pydatalab/pyproject.toml
- pydatalab/src/pydatalab/apps/raman/blocks.py
- pydatalab/src/pydatalab/apps/xrd/blocks.py
- pydatalab/tests/apps/test_raman.py
This PR updates the Raman tests to check for peak positions, localises and capture warnings when doing baseline corrections for XRD/Raman and more robustly parses units out of Raman data files.
> Improve 1D Raman tests and extract more information from file headers

- pydatalab/pyproject.toml
- pydatalab/src/pydatalab/backups.py
- pydatalab/uv.lock
The built-in backup functionality had an option to specify are remote hostname to connect to via SFTP. This was never used by anyone and is not well-tested, so I believe it can safely be removed (as it is superseded by the borg functionality in the ansible playbooks).
> Remove untested remote backup functionality and dependency on paramiko

- pydatalab/pyproject.toml
- pydatalab/src/pydatalab/apps/raman/blocks.py
- pydatalab/tests/apps/test_raman.py
- pydatalab/uv.lock
Rosettasciio's licensing is still up for discussion (https://github.com/hyperspy/rosettasciio/issues/51). To be on the safe side of GPL wrt. whether including it as a dependency constitutes "linking" or "aggregation" on the Python side, let's defer back to the original MIT licensed package that the Rosetta version is based on.
This seems to work fine for 1D spectra at least, though might need to put in some work to extract offsets to ensure consistency, even if we're not entirely sure what these offsets entail.
> Switch Raman block to use `renishawWire` package

- pydatalab/src/pydatalab/config.py
- pydatalab/src/pydatalab/routes/v0_1/items.py
- webapp/src/components/BatchCreateItemModal.vue
Closes #1070 
window.alert() will be replaced with new composant from #1212
> Limit batch interface to 100 items in UI and 10,000 via API

- .github/workflows/ci.yml
- .github/workflows/license-check.yml
- pydatalab/pyproject.toml
- pydatalab/uv.lock
This PR updates the liccheck ignores to include galvani, and calls the workflow every PR.
> Fix liccheck workflow and dependency ignores

- pydatalab/src/pydatalab/models/starting_materials.py
- pydatalab/tests/server/test_starting_materials.py
Reported by @PeterKraus, this was causing weird errors when setting chemical formulae to e.g, `Xe/Ar`, which was failing to be turned into a molar mass by `periodictable` (and the error returned was no longer being caught).
> Fix for molar mass validation with invalid formula of starting materials

- CHANGELOG.md
- README.md
- pydatalab/mkdocs.yml
- pydatalab/pyproject.toml
- pydatalab/uv.lock
Update changelog with 0.6.0 changes, and make a few docs tweaks.
Closes #1241 and #1196.
> Prepare 0.6.0 release

- pydatalab/tests/server/test_blocks.py
Closes #1191 
Add tests for the block API in a new test module `tests/server/test_blocks.py`.
> Add exhaustive block API testing for all block types

- pydatalab/pyproject.toml
- Add description and keywords for PyPI
- Author metadata is a bit janky when provided by pyproject.toml (it would only show @jdbocarsly's name with my email) so I've just pulled it back to "datalab dev team" with a generic email (that gets forwarded).
> Fix some PyPI metadata

- webapp/package.json
- webapp/vue.config.js
- webapp/yarn.lock
This PR removes the stream polyfill that is required by parts of uppy. As we are using XHR with Uppy, I don't think we need this (and its an annoying dependency to have).
> Remove browersify stream polyfill

- pydatalab/pyproject.toml
- pydatalab/src/pydatalab/apps/uvvis/__init__.py
- pydatalab/src/pydatalab/apps/uvvis/utils.py
- pydatalab/tests/apps/test_plugins.py
- pydatalab/tests/apps/test_uvvis.py
- pydatalab/uv.lock
- webapp/src/components/FolderSelect.vue
- webapp/src/components/datablocks/UVVisInsituBlock.vue
- webapp/src/resources.js
Adds a custom component for the new in situ UV-vis block that closely mirrors the in situ NMR block.
> Add custom UI for new in situ UV-Vis block

- webapp/cypress/e2e/batchSampleFeature.cy.js
- webapp/src/components/CompactConstituentTable.vue
- webapp/src/components/FormattedItemName.vue
- webapp/src/components/SynthesisInformation.vue
Closes #1278
The `vs__dropdown-menu` was getting cut off because the parent container had `overflow: hidden` for the collapse/expand animation
> Fix item selection dropdown missing scrollbar in synthesis info

- pydatalab/schemas/cell.json
- pydatalab/schemas/equipment.json
- pydatalab/schemas/sample.json
- pydatalab/schemas/startingmaterial.json
- pydatalab/src/pydatalab/models/blocks.py
- pydatalab/src/pydatalab/models/traits.py
In trying to ablate changes from #1285 that are not entirely necessary, I've found it helpful to define a model for the blocks response when it is embedded in an item.
> Add `DataBlockResponse` model to sanitize `blocks_obj` in API

- webapp/cypress/support/commands.js
- webapp/src/App.vue
- webapp/src/components/BatchCreateItemModal.vue
- webapp/src/components/CollectionSelect.vue
- webapp/src/components/CreateCollectionModal.vue
- webapp/src/components/CreateEquipmentModal.vue
- webapp/src/components/CreateItemModal.vue
- webapp/src/components/DialogContainer.vue
- webapp/src/components/DialogModal.vue
- webapp/src/components/DynamicDataTableButtons.vue
- webapp/src/components/EditAccountSettingsModal.vue
- webapp/src/components/FileList.vue
- webapp/src/components/ToggleableCreatorsFormGroup.vue
- webapp/src/components/UserTable.vue
- webapp/src/components/datablocks/DataBlockBase.vue
- webapp/src/file_upload.js
- webapp/src/main.js
- webapp/src/server_fetch_utils.js
- webapp/src/services/DialogService.js
- webapp/src/views/CollectionPage.vue
- webapp/src/views/EditPage.vue
Closes #1180 
This PR replaces all browser-native alert and confirm dialogs (`window.confirm`) with custom Datalab components.
Uses a DialogService that manages dialogs and displays them through Vue components
Implemented 4 different modal styles to match various use cases:
- Error:
- Warning:
- Info:
- Success:
> Replace browser-native dialogs with custom datalab dialog service

- CHANGELOG.md
- pydatalab/pyproject.toml
- pydatalab/schemas/cell.json
- pydatalab/schemas/equipment.json
- pydatalab/schemas/sample.json
- pydatalab/schemas/startingmaterial.json
- pydatalab/src/pydatalab/apps/chat/blocks.py
- pydatalab/src/pydatalab/apps/chat/models.py
- pydatalab/src/pydatalab/apps/nmr/blocks.py
- pydatalab/src/pydatalab/apps/xrd/blocks.py
- pydatalab/src/pydatalab/blocks/base.py
- pydatalab/src/pydatalab/models/blocks.py
- pydatalab/src/pydatalab/routes/v0_1/blocks.py
- pydatalab/src/pydatalab/routes/v0_1/items.py
- pydatalab/tests/apps/test_chat.py
- pydatalab/tests/apps/test_nmr.py
- pydatalab/tests/server/conftest.py
- pydatalab/tests/server/test_blocks.py
- webapp/src/server_fetch_utils.js
This PR initially just updated the "all blocks" test to separate out each block and make sure that they were all doing something sensible. However, I realised that without the app to pass block data back in `update-block` calls, some of the block results was not being saved in the database. This PR fixes that by explicitly calling `_save_to_db` after every block creation call, making the `save_to_db` option somewhat defunct.
Following the principle of least suprise, I think the previous undocumented behaviour (i.e., being able to essentially see a block in an unsaved state) was not expected, so the only side effect here should be improved persistence.
In order to properly implement this, block operations now go through the new `DataBlockResponse` model introduced in #1310, which we can …
> Validate block database save/export operations with `DataBlockResponse` model

- .docker/server_dockerfile
- docker-compose.yml
Refactor Docker configuration to allow users to customize gunicorn settings via GUNICORN_CMD_ARGS environment variable while maintaining sensible defaults for WEB_CONCURRENCY, timeouts, and logging.
Closes #1333
I gave up trying to avoid repeating the default values of the various `ENV` statements.
> Refactor Docker gunicorn configuration for better flexibility

- pydatalab/src/pydatalab/apps/chat/blocks.py
- pydatalab/src/pydatalab/apps/chat/models.py
Closes #1339. 
Previously the chatblock was storing the `available_models` list per block in the database, but the new chatblock model introduced recently stopped this, so we need to use the default values instead.
> Chat block fix: ignore available models list based on web app update

- CHANGELOG.md
I tried to rush a v0.6.3-rc.1 release and accidentally released it as v0.6.3 proper -- no big deal, but this PR tidies up that process and adds the latest changes to the changelog.
> Update changelog for v0.6.3
