.readthedocs.yaml, README.md, mkdocs.yml, pydatalab/docs/schemas/cells.md
This PR adds some README badges now we are open.
=> Deploy docs on RTD and add README badges

README.md
No need for review, purely aesthetic
=> Use logos in README badges

INSTALL.md, README.md, docker-compose.yml, pydatalab/setup.py, webapp/cypress/e2e/batchSampleFeature.cy.js, webapp/cypress/e2e/editPage.cy.js, webapp/cypress/e2e/sampleTablePage.cy.js, webapp/package.json, webapp/src/App.vue, webapp/src/components/Creators.vue, webapp/src/components/Navbar.vue, webapp/src/components/SampleInformation.vue, webapp/src/components/SampleTable.vue, webapp/src/components/StartingMaterialTable.vue, webapp/src/components/UserBubble.vue, webapp/src/main.js, webapp/src/views/About.vue, webapp/yarn.lock
This PR adds several UI tweaks:
Closes #277 and #262
=> UI tweaks and refactors

pydatalab/pydatalab/blocks/echem_block.py, pydatalab/pydatalab/bokeh_plots.py, pydatalab/pydatalab/logger.py, pydatalab/tests/blocks/test_echem_block.py, webapp/src/components/datablocks/CycleBlock.vue
=> Add cycle vs capacity plots to echem block

pydatalab/pydatalab/blocks/blocks.py
This PR simply fixes linting issues introduced in the last commit.
=> Fix linting

pydatalab/pydatalab/bokeh_plots.py
Doesn't actually deal with #315 -- but adds the save functionality to get a png of a plot
=> Enable Bokeh save tool

pydatalab/pydatalab/errors.py, pydatalab/scripts/migrate_image_blocks_to_media_blocks.py, pydatalab/tasks.py
=> Minor fixes and relinting

webapp/src/components/CellInformation.vue, webapp/src/components/FileSelectModal.vue, webapp/src/components/SelectableFileTree.vue
Bit worried that a117039f04165db710c6b8fcb0cfd41faabe624e didn't get caught by prettier etc!
To-do/fix:
=> Minor web app fixes

webapp/src/resources.js
tiny change for consistency in the UI
=> rename media block -> media

pydatalab/pydatalab/apps/eis/__init__.py, pydatalab/pydatalab/blocks/__init__.py, pydatalab/pydatalab/blocks/blocks.py, pydatalab/pydatalab/bokeh_plots.py, webapp/public/index.html, webapp/src/components/datablocks/EISBlock.vue, webapp/src/resources.js
Plots EIS data from Ivium `.txt` files, with a few additional changes to the `selectable_axis_plot` (will clash with #276).
=> Add simple Ivium EIS block

pydatalab/Pipfile, pydatalab/Pipfile.lock, pydatalab/pydatalab/blocks/echem_block.py, pydatalab/pydatalab/bokeh_plots.py, pydatalab/pydatalab/routes/v0_1/items.py, pydatalab/pydatalab/utils.py, pydatalab/tests/blocks/test_echem_block.py, pydatalab/tests/conftest.py, pydatalab/tests/routers/test_samples.py, webapp/src/components/itemCreateModalAddons/SampleCreateModalAddon.vue
=> Assorted echem tweaks and fixes

pydatalab/pydatalab/bokeh_plots.py
=> Fix off-by-one error in echem plot colouring that was breaking filtering

webapp/src/components/TreeMenu.vue
=> Add `@click.ctrl` for multi-file select in remote sync

pydatalab/pydatalab/apps/xrd/blocks.py, pydatalab/tests/blocks/test_xrd_block.py
=> Fix XRD plot wavelength interaction

pydatalab/pydatalab/blocks/echem_block.py
Addresses but does not close #425
=> Adjust default echem subsampling

README.md, webapp/src/views/About.vue
=> Fix broken README link and update affiliations

pydatalab/pydatalab/login.py, pydatalab/pydatalab/routes/v0_1/auth.py
=> Fix bug where user cannot be created with blank display name

README.md, mkdocs.yml
Update font and improve link rendering.
=> Tweak to deployed documentation

pydatalab/pydatalab/file_utils.py, pydatalab/pydatalab/routes/v0_1/files.py
=> Fix file permissions issues

pydatalab/docs/config.md
=> Add note about GitHub callback URL in docs

.github/workflows/ci.yml
This PR simply runs the e2e tests in both Firefox and Chrome after the default electron run.
=> Additionally e2e test Firefox & Chrome by default

.pre-commit-config.yaml, pydatalab/docs/config.md, pydatalab/pydatalab/apps/raman/blocks.py, pydatalab/pydatalab/apps/xrd/blocks.py, pydatalab/pydatalab/config.py, pydatalab/pydatalab/routes/v0_1/auth.py, pydatalab/tests/routers/test_files.py, pyproject.toml
Just need to test this on the dev server before merging.
=> Improve GitHub OAuth connection

pydatalab/pydatalab/routes/v0_1/auth.py
=> Fix scope order for GitHub OAuth app

pydatalab/pydatalab/config.py
=> Generate default `SECRET_KEY` from platform-specific info

pydatalab/pydatalab/config.py, pydatalab/pydatalab/main.py
First of the PRs to break up #484 to try to debug the e2e tests.
=> Make Flask session lifetime configurable

pydatalab/docs/config.md
Minor change updating the docs about scheduled backups.
=> Update backup docs

.docker/server_dockerfile
=> Upgrade mdbtools per new galvani version

pydatalab/pydatalab/apps/eis/__init__.py, pydatalab/pydatalab/apps/nmr/blocks.py, pydatalab/pydatalab/apps/xrd/blocks.py, pydatalab/pydatalab/bokeh_plots.py, webapp/cypress.config.ts, webapp/cypress/e2e/batchSampleFeature.cy.js, webapp/cypress/e2e/editPage.cy.js, webapp/cypress/e2e/sampleTablePage.cy.js, webapp/cypress/support/commands.js, webapp/src/App.vue, webapp/src/components/BokehPlot.vue, webapp/src/components/CellInformation.vue, webapp/src/components/CompactConstituentTable.vue, webapp/src/components/FileSelectDropdown.vue, webapp/src/components/FormattedCollectionName.vue, webapp/src/components/FormattedItemName.vue, webapp/src/components/ItemSelect.vue, webapp/src/components/Navbar.vue, webapp/src/components/SampleInformation.vue, webapp/src/components/datablocks/CycleBlock.vue, webapp/src/components/datablocks/NMRBlock.vue, webapp/src/components/datablocks/XRDBlock.vue, webapp/src/views/EditPage.vue
A few style cleanups and improvements:
- Some CSS cleanup
- Some CSS changes
- Add placehold text to ItemSelect to make it more clear what it is for
- Improve ergonomics and look of compact constituent table
- Improve styling of blocks; fix some awkward spacing, sizing, and alignment
- Add a message about allowed extensions to the FileSelectDropdown
- Change descriptions of EIS and NMR block
- Hide block options (e.g. wavelength, cycles to plot, etc.) until a file is selected
=> Visual style improvements, test updates and improved block UI

pydatalab/Pipfile, pydatalab/Pipfile.lock, pydatalab/pydatalab/apps/echem/blocks.py, webapp/src/components/datablocks/CycleBlock.vue
Bumps navani, galvani and adds NewareNDA, plus other deps because pipenv hates us
Closes #537 and relates to https://github.com/the-grey-group/navani/issues/10 where some mpr files could not be read. Closes #618 
Both of these updates rely on my forks, which will need to be updated once packages are merged and released upstream.
=> Add Neware support and fix MPR issue

.github/workflows/ci.yml, pydatalab/Pipfile, pydatalab/Pipfile.lock
=> Use newly released galvani and NewareNDA packages

pydatalab/pydatalab/routes/v0_1/auth.py
Related to #576 (cc @BenjaminCharmes)
=> Return user role from `/get-current-user` endpoint

pydatalab/pydatalab/bokeh_plots.py
Begins addressing #359.
Closes #359.
=> Add ability to generate .csv files within block callbacks

.docker/app_dockerfile, .docker/app_entrypoint.sh, docker-compose.yml
This could have been added to the inventory PR but it wasn't.
=> Add default config for `VUE_APP_EDITABLE_INVENTORY`

pydatalab/pydatalab/routes/v0_1/items.py
=> Allow starting materials and equipment to be edited by normal users

pydatalab/pydatalab/apps/nmr/blocks.py
=> Fix NMR block layout issue

webapp/src/components/AdminDisplay.vue, webapp/src/components/AdminNavbar.vue, webapp/src/components/LoginDetails.vue, webapp/src/components/NotificationDot.vue, webapp/src/components/UserTable.vue, webapp/src/views/Admin.vue
- Improved the navbar in the admin dashboard
- Improved banner for unverified accounts
- Improved text in the notification-dot
=> Improve admin dashboard styling and functionality

pydatalab/pydatalab/config.py, pydatalab/pydatalab/routes/v0_1/auth.py
Closes #205 -- just giving up and making this a config variable, which can in the future be "upgraded" to a setting in #704.
=> Add `CONFIG.APP_URL` to allow for customisable redirects on login/registration

.pre-commit-config.yaml, CHANGELOG.md, pydatalab/docs/.pages, pydatalab/docs/CHANGELOG.md
=> Add CHANGELOG to repo and docs

pydatalab/Pipfile.lock
Simply patch a few deps that dependabot has warned us about.
=> Update a few (midly) insecure deps

pydatalab/tasks.py
=> Remove cheminventory import task (which is now in `datalab-api`)

webapp/src/components/ChemicalFormula.vue
We should disable this until we can do a proper pass on it.
Closes #208 (temporarily)
Blocked by #805
=> Disable `ChemicalFormula` component

.github/utils/update_docs.sh, .github/workflows/ci.yml, CHANGELOG.md
=> Try to group cypress tests in same run

webapp/src/views/Collections.vue, webapp/src/views/Equipment.vue, webapp/src/views/SamplePrime.vue, webapp/src/views/Samples.vue, webapp/src/views/SamplesNext.vue, webapp/src/views/StartingMaterials.vue
This PR removes unused css attributes from multiple files
=> Removed unused css

README.md, pydatalab/pydatalab/routes/v0_1/collections.py, pydatalab/pydatalab/routes/v0_1/items.py, pydatalab/pydatalab/send_email.py
Just tidying up some code that still mentions the old domain, and updating the README badge for the public deployment.
=> Remove final mentions of odbx.science

webapp/src/components/EditAccountSettingsModal.vue
=> Do not show option to connect accounts in acocunt settings if not configured in server

webapp/src/components/LoginDetails.vue, webapp/src/components/LoginDropdown.vue, webapp/src/components/Navbar.vue, webapp/src/components/UserDropdown.vue
Closes #768.
Also adds a patch that helps development cfgs by allowing non-fatal vue/prettier errors to appear as warnings.
=> Refactor login components

pydatalab/pydatalab/routes/v0_1/collections.py, pydatalab/tests/server/test_graph.py, pydatalab/tests/server/test_samples.py, webapp/src/components/AddToCollectionModal.vue, webapp/src/components/SampleTablePrime.vue, webapp/src/server_fetch_utils.js
Closes #819 
Add functionality to /collections route to receive and add a list of items to a list of collections inside the new next DataTable for samples
=> Add API route to add items to a collection and associated UI

webapp/cypress/support/commands.js
There are some flaky test failures introduced by #885. This PR partially reverts one of the testing changes to see if it has an effect.
=> Hotfix for new e2e test command

webapp/src/components/DynamicDataTable.vue
=> Fix SelectAll issue in DataTable after search 

.github/workflows/dependable-bot.yml, .github/workflows/yarn-upgrade-bot.yml
Follows the example set in #945, which is working well. Again, I'll merge this and try to manually trigger the workflow.
=> Add scheduled `yarn upgrade` job in CI

pydatalab/src/pydatalab/file_utils.py, pydatalab/src/pydatalab/routes/v0_1/files.py, webapp/src/components/FileList.vue, webapp/src/components/FileSelectDropdown.vue, webapp/src/file_upload.js, webapp/src/server_fetch_utils.js, webapp/src/store/index.js, webapp/src/views/EditPage.vue
This PR reworks some of the file upload handling in the app and API, particularly how file metadata is used in the vuex store, and where the file update methods get called. The API remains unchanged beyond some minor refactoring for clarity (and extra defensiveness on permissions).
=> Rework of the files utilities and endpoints for both app and API

pydatalab/src/pydatalab/config.py, pydatalab/src/pydatalab/errors.py, pydatalab/tests/server/conftest.py, pydatalab/tests/server/test_files.py
=> Fix default `MAX_CONTENT_LENGTH` setting to 10 GB

webapp/cypress.config.ts, webapp/cypress/e2e/editPage.cy.js, webapp/cypress/fixtures/example.json, webapp/cypress/support/commands.js, webapp/src/components/datablocks/MediaBlock.vue
=> Fix and streamline attribute lookup in MediaBlock

pydatalab/src/pydatalab/apps/chat/blocks.py
Closes #985 
Guess we can decide whether we want to keep Claude-3-Opus (now surpassed by 3.5 Haiku) and Claude-3-Sonnet, but I've left claude-3-haiku in as its 4x cheaper than the new haiku.
@jdbocarsly may have the strongest opionions...
=> Add latest Claude models

pydatalab/src/pydatalab/routes/v0_1/info.py, pydatalab/tests/server/test_info_and_health.py, webapp/src/server_fetch_utils.js
=> Add API endpoint for reporting schemas

webapp/src/components/CollectionTable.vue, webapp/src/components/Creators.vue, webapp/src/components/DynamicDataTable.vue, webapp/src/components/DynamicDataTableButtons.vue, webapp/src/components/SampleTable.vue, webapp/src/primevue-theme-preset.js
Related to #889
Closes #973 
Enhanced filtering for Creators and Collections column
=> Enhanced filtering UI on fields with components

webapp/src/components/DynamicDataTable.vue, webapp/src/components/DynamicDataTableButtons.vue
=> Allow both search and filter to be specified simultaneously in entry table

webapp/cypress/component/CollectionTableTest.cy.jsx, webapp/cypress/component/EquipmentTableTest.cy.jsx, webapp/cypress/component/SampleTableTest.cy.jsx, webapp/cypress/component/StartingMaterialTableTest.cy.jsx, webapp/src/components/DynamicDataTable.vue, webapp/src/store/index.js
Closes #983
Store the current page and the number of rows of each page in the vuex store
=> Improve DataTable Pagination Handling with Vuex

pydatalab/src/pydatalab/permissions.py, pydatalab/tests/server/test_starting_materials.py
Closes #880 and #835, until we refactor the permissions system again.
I want to add some more solid unit tests to this before releasing.
=> Add patch for starting material & equipment permissions

CHANGELOG.md
=> Add CHANGELOG for 0.5.0

webapp/cypress/e2e/editPage.cy.js, webapp/src/components/datablocks/DataBlockBase.vue
Closes  #1045
First attempt to improve the loading state for data-intensive blocks
=> Improve loading state for data-intensive blocks

pydatalab/pyproject.toml, pydatalab/src/pydatalab/blocks/__init__.py, pydatalab/tests/apps/test_plugins.py, pydatalab/uv.lock, webapp/src/components/datablocks/NMRInsituBlock.vue, webapp/src/resources.js
Add a new Insitu NMR DataBlock using new [datalab insitu plugin](https://github.com/datalab-org/datalab-app-plugin-insitu)
=> Add in situ NMR DataBlock as an app plugin

webapp/src/components/StyledBlockHelp.vue
Closes #1085 
Should be enough to handle docstrings
=> Wrap block descriptions into block menu

webapp/src/components/FileSelectDropdown.vue, webapp/src/components/datablocks/MediaBlock.vue
Closes #1090 and closes #1036.
=> Allow case-insensitive file extensions through file select dropdown

webapp/src/components/datablocks/MediaBlock.vue
=> Make media block resizable

pydatalab/pyproject.toml, pydatalab/src/pydatalab/blocks/__init__.py, pydatalab/tests/apps/test_plugins.py, pydatalab/uv.lock, webapp/src/components/datablocks/DataBlockBase.vue, webapp/src/components/datablocks/NMRInsituBlock.vue
Closes #1084 
`insitu-nmr` plugin is correctly loaded on server startup. 
Updates plugin name in `resources.js` and `NMRInsituBlock.vue`
[WIP]:
- Need to understand why these changes make tests failed
=> Fix plugin loading not triggering on server startup

webapp/cypress/component/GHSInformationTest.cy.jsx, webapp/src/resources.js, webapp/yarn.lock
=> Add tests for hazard statement -> H-code -> pictogram mappings

pydatalab/pyproject.toml, pydatalab/src/pydatalab/blocks/__init__.py, pydatalab/tests/apps/test_plugins.py, pydatalab/uv.lock
=> Use `importlib` for plugin loading, fix test import order

webapp/src/components/DynamicDataTable.vue
=> Default to opening a new tab when clicking on the sample table

pydatalab/src/pydatalab/apps/nmr/blocks.py, pydatalab/src/pydatalab/apps/nmr/utils.py, pydatalab/src/pydatalab/apps/xrd/utils.py, pydatalab/tests/apps/test_nmr.py, webapp/src/components/datablocks/NMRBlock.vue
Main one being using a temp dir when extracting data, to avoid clogging up the server.
Also improve the NMR block plots and nest metadata under their own key (which the app will now try to use by default in the UI, falling back to the original).
=> NMR and XRD block improvements

pydatalab/src/pydatalab/mongo.py, pydatalab/src/pydatalab/routes/v0_1/items.py, pydatalab/tests/server/conftest.py, pydatalab/tests/server/test_samples.py
=> Make the regex item search the default, and use '%' for full text search

.docker/app_dockerfile, .github/workflows/ci.yml
A lot of fuss to save a couple of minutes in the CI again... but at least caching now works more reliably.
=> CI build optimisations

.github/workflows/yarn-upgrade-bot.yml, webapp/yarn.lock
This reverts commit 799aaf686333870c4fb29b9d1d51da9331163b9c, due to various issues #1142 / #1140 / #1141
=> Revert JS dependency updates

webapp/cypress/component/SampleTableTest.cy.jsx, webapp/src/components/SampleTable.vue
Closes #1139
I may have missed some things to test, so don't hesitate to tell me and I'll add them!
=> Add searching, filtering and sorting test in Datatable

webapp/src/components/DynamicDataTable.vue, webapp/src/components/DynamicDataTableButtons.vue
Closes #1113 & #1135
Use localStorage in DataTable to store:
- which column are displayed/hide
- width of each column
=> Use localStorage for persistent column hiding in Datatable

pydatalab/src/pydatalab/routes/v0_1/items.py, pydatalab/tests/server/test_samples.py, webapp/cypress/component/StartingMaterialTableTest.cy.jsx, webapp/src/App.vue, webapp/src/components/BarcodeModal.vue, webapp/src/components/CollectionInformation.vue, webapp/src/components/CollectionTable.vue, webapp/src/components/CompactConstituentTable.vue, webapp/src/components/DynamicDataTable.vue, webapp/src/components/EquipmentTable.vue, webapp/src/components/FormattedBarcode.vue, webapp/src/components/FormattedRefcode.vue, webapp/src/components/SampleTable.vue, webapp/src/components/StartingMaterialInformation.vue, webapp/src/components/StartingMaterialTable.vue, webapp/src/components/SynthesisInformation.vue, webapp/src/main.js
This PR improves the inventory table with:
Also:
- closes #1174 by properly restricting types in item search.
- ~closes #1175 by allowing refcodes to be passed to create sample, but only to check if they already exist~
=> Quality of life updates to the inventory: barcode display, richer data table

pydatalab/src/pydatalab/routes/v0_1/items.py
=> Better handling of duplicate key errors in item creation

webapp/src/components/DynamicDataTable.vue
=> Fix DataTable select-all when sorting is applied

webapp/src/components/CollectionInformation.vue
=> Give collection title and creators list their own rows

pydatalab/example_data/XRD/cod_9004112.cif, pydatalab/pyproject.toml, pydatalab/src/pydatalab/apps/xrd/blocks.py, pydatalab/src/pydatalab/apps/xrd/models.py, pydatalab/src/pydatalab/apps/xrd/utils.py, pydatalab/src/pydatalab/file_utils.py, pydatalab/tests/apps/test_xrd_block.py, pydatalab/uv.lock, webapp/src/components/FileSelectDropdown.vue, webapp/src/components/datablocks/XRDBlock.vue, webapp/src/store/index.js
Closes #1120 by adding a [matador](https://github.com/ml-evs/matador)-based PXRD calculator for CIF files.
Bonus: record peak information in database where possible, and update `FileSelectDropdown` to allow for "All compatible files" option to be turned on.
=> Add CIF->PXRD calculator and refactor XRD block to better show multiple patterns

pydatalab/docs/config.md, pydatalab/docs/deployment.md
=> Avoid mentioning specific version in deployment docs and list `VUE_APP_*` env vars

pydatalab/src/pydatalab/models/cells.py, pydatalab/src/pydatalab/models/relationships.py, pydatalab/src/pydatalab/models/traits.py, pydatalab/src/pydatalab/models/utils.py
Closes #1173
Stock item_id and refcode in the db, but refcode has priority.
=> Add relationships by `refcode` rather than `item_id` from the UI

pydatalab/docs/config.md
=> Add note about inconsistencies in ways configs are specified

webapp/src/components/SampleTable.vue
=> Add creators in SampleTable global search

pydatalab/src/pydatalab/errors.py, pydatalab/src/pydatalab/routes/v0_1/auth.py, pydatalab/src/pydatalab/routes/v0_1/graphs.py, pydatalab/src/pydatalab/routes/v0_1/healthcheck.py, pydatalab/src/pydatalab/routes/v0_1/items.py, pydatalab/src/pydatalab/routes/v0_1/remotes.py, pydatalab/tests/server/test_files.py, pydatalab/tests/server/test_starting_materials.py
=> Lift restriction on passing item type when updating via `/save-item`

pydatalab/docs/config.md
=> Update SMTP integration to recommend resend.com

pydatalab/src/pydatalab/blocks/common.py
=> Fix case-sensitivity of media block TIF handling
